apiVersion: v1
kind: Pod
metadata:
  name: notebook
  namespace: haste
  labels:
    name: notebook
spec:
  containers:
  - image: benblamey/hom-impl-2.cp-notebook:latest
    # image is local-only atm.
    imagePullPolicy: Always
    name: notebook
    resources:
      limits:
        cpu: 20000m
        ephemeral-storage: 10Gi
        memory: 10024Mi
      requests:
        cpu: 50m
        ephemeral-storage: 1Mi
        memory: 256Mi
    command: ["python3"]
    args: ["-m","jupyterlab","--no-browser","--ServerApp.password='argon2:$argon2id$v=19$m=10240,t=10,p=8$LKoe+YVbK+qMsaH87iMiLQ$XroRerX0xeyPoBB1Ik2odA'","--allow-root","--notebook-dir","/data","--ip=*","--ServerApp.base_url","/notebook/"]
    volumeMounts:
    - mountPath: /data
      name: volume-hom-pv-data
    - mountPath: /images
      name: volume-hom-pv-images
  volumes:
  - name: volume-hom-pv-data
    persistentVolumeClaim:
      claimName: haste-pvc
  - name: volume-hom-pv-images
    persistentVolumeClaim:
      claimName: micro-images-pvc
  restartPolicy: Always